### ISSUE TITLE
Differentiate oauthdebugger and oidcdebugger

### ISSUE THREAD

**Issue by gabrielsroka** [nbarbettini/oidc-debugger#32]
are oidcdebugger.com and oauthdebugger.com both running the same code? i would have thought oauth wouldn't include oidc-specific things like the "openid" scope, the id_token, etc.

**Comment by nbarbettini** [comment]
Yeah, there are a few places that I missed:

- [ ] "The openid scope is the only required scope"
- [ ] id_token response type
